Add GFO-light minimal version
Onto-Med/GFO pull request #34
Opened 2024-09-02 12:10 UTC by AlexU75

2024-09-02 13:02 UTC, ChristophB approved these changes
To improve readability, consider additional text formatting for class names etc. in the paragraphs.

2024-09-05 09:43 UTC, KonradHoeffner requested changes
I submitted some suggestions in <https://github.com/Onto-Med/GFO/pull/35>. Please tell me if there is a more efficient way to accomplish this with the GitHub web pull request interface :-)
This is an initial review with a quick glance, I can do a more thorough review later if required looking into the semantics of the example and so on.

2024-09-05 09:44 UTC, KonradHoeffner commented
P.S.: @AlexU75: I think there is something wrong with the line endings settings, I keep getting Windows line endings when checking out files from your computer, but this does not seem happen when I check out files from other Windows users.

2024-11-20 11:36 UTC, k00ni commented
What is the status here? As an outsider who has some GFO knowledge it is very helpful to have a GFO-light variant around.

2024-11-20 11:40 UTC, k00ni commented on gfo-light.ttl
> +@prefix : <https://w3id.org/gfo/light/> .
Why introducing the new RDF content in a different serialization (RDF/Turtle)? Existing RDF content is RDF/XML.

2024-11-28 12:15 UTC, k00ni commented on gfo-light.ttl
> +@prefix xml: <http://www.w3.org/XML/1998/namespace> .
```suggestion
```
`xml` prefix is never used and can be removed safely.

2024-11-28 12:24 UTC, k00ni commented
Having played around with `gfo-light.ttl` for a while I wonder why introducing a new namespace?

* **gfo-base**: `https://w3id.org/gfo/base`
* **gfo-light**: `https://w3id.org/gfo/light` :new:

Isn't `gfo-light` just a "sub graph" of gfo-base? To me it always appeared that you only picked a few classes, properties and axioms from gfo-base and bundling it to gfo-light.

Developing with gfo-light might be "easier", because there is less stuff and its more clear but what do I do when I want to use stuff from gfo-base? Do I have to replace my namespace or are there even more changes behind the scenes I have to be aware of?

2024-11-28 15:26 UTC, KonradHoeffner commented
> > It would indeed be very helpful if you could use a version scheme such as [Semantic Versioning](https://semver.org/).
> 
> We discussed this internally. Personally, I also prefer semantic versioning, but the decision was to use date-based version numbers.

May I suggest [CalVer](https://calver.org/) so you can have both at the same time? :-)

2025-01-08 12:41 UTC, k00ni commented on examples/gfo-light-football-match-exam.ttl
> + ] .
This looks weird. Is that intentional or could this be removed?

2025-01-08 13:17 UTC, ChristophB commented on examples/gfo-light-football-match-exam.ttl
> + ] .
Fixed in [ea697b2](https://github.com/Onto-Med/GFO/pull/34/commits/ea697b2d7559322ef173273b35319f02dbecf15a)

2025-01-09 09:10 UTC, KonradHoeffner commented
The ontology diagrams have a lot of white space in them, which means they either use up a lot of space in a paper or poster or will be too small to read if they are scaled down to counteract this.

I see two options here:

1. Save vertical space by moving Entity-Category-Individual to the lower right.
2. Save horizontal space by moving Entity-Category-Individual from the upper right to the upper left and moving Process, TimeEntity, Chronoid and TimeBoundary to the upper right.

2025-01-09 09:55 UTC, KonradHoeffner commented
Improved version
![gfo-light-compact-vertical](https://github.com/user-attachments/assets/637edeb3-7f86-40c8-9925-6e36c183c5ad)
[gfo-light-compact-vertical.zip](https://github.com/user-attachments/files/18359663/gfo-light-compact-vertical.zip)

2025-01-09 12:08 UTC, AlexU75 commented
> The ontology diagrams have a lot of white space in them, which means they either use up a lot of space in a paper or poster or will be too small to read if they are scaled down to counteract this.

For documentation purposes, I find the original graphic (as a tree) easier to understand. We can then use the compact one for papers, posters, etc.

2025-01-10 09:03 UTC, KonradHoeffner approved these changes
My requested changes have been merged.

2025-01-10 10:27 UTC, ChristophB approved these changes
Please see #55 for some minor changes.

2025-01-13 11:10 UTC, ChristophB commented on docs/gfo-light.md
As stated by @AlexU75:
> Material continuants subsume material objects, material aggregates and material parts.

But I think the sentence is a bit too long/complex. We could write something like:

> Material continuants ~are~ **subsume** individual 3-dimensional material objects (e.g., a person, a computer, a chopstick or a football stadium), material aggregates (groups) of objects that together form a unit (e.g., a research group at a university or a sports team) ~or~ **and** material parts that have no natural boundary with the whole material object (e.g., part of a bone or of a chopstick).

Or to make it easier to read:

> Material continuants subsume the following:
> * individual 3-dimensional material objects (e.g., a person, a computer, a chopstick or a football stadium)
> * material aggregates (groups) of objects that together form a unit (e.g., a research group at a university or a sports team)
> * material parts that have no natural boundary with the whole material object (e.g., part of a bone or of a chopstick)

2025-01-13 11:11 UTC, ChristophB commented on gfo-light.ttl
> +@prefix : <https://w3id.org/gfo/light/> .
> Why introducing the new RDF content in a different serialization (RDF/Turtle)?

2025-01-13 12:31 UTC, AlexU75 commented on docs/gfo-light.md
@ChristophB The second variant is good, please change it.

2025-01-13 12:44 UTC, ChristophB commented on docs/gfo-light.md
Fixed with [68e1ce8](https://github.com/Onto-Med/GFO/pull/34/commits/68e1ce844325c081478737be5b3eec1e1066cdb7)

2025-01-20 13:06 UTC, ChristophB commented on gfo-light.owl
There is a reference to this file in the section "Further Documentation" in `README.md`.

2025-01-20 13:09 UTC, ChristophB commented on gfo-light.owl
Fixed in [d9210a2](https://github.com/Onto-Med/GFO/pull/34/commits/d9210a26880a848cb5512fe90c70a1994f2ff8b6)

2025-02-06 09:35 UTC, ChristophB commented
On Friday 6 February, I will:
- move all changes in the branch to https://github.com/Onto-Med/gfo-light (currently private, will be set to public on Friday as well)
- update this pull request to remove GFO-light stuff from this repository
- add a short reference to GFO-light into `README.md`

2025-02-07 12:35 UTC, ChristophB commented
GFO-light is now maintained here: https://github.com/Onto-Med/gfo-light

2025-02-07 12:35 UTC, closed without merging